# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Poorva Nangia
email: poorvanangia03@gmail.com
description: null
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://poorvanangia.com" # the base hostname & protocol for your site
linkedin_username: poorvanangia
paginate: 3

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
